### ISSUE TITLE
Serializing Login data stuff

### ISSUE THREAD

**Issue by OGarland001** [OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1#18]
System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
  Source=System.Runtime.Serialization.Formatters
  StackTrace:
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Server.Packet..ctor(Byte[] data) in C:\Users\oweng\OneDrive\Desktop\Project-IV\ProjectFiles\Server\Packet.cs:line 153
   at Server.ProgramServer.run() in C:\Users\oweng\OneDrive\Desktop\Project-IV\ProjectFiles\Server\Server.cs:line 50
   at Server.MainWindow..ctor() in C:\Users\oweng\OneDrive\Desktop\Project-IV\ProjectFiles\Server\InterfaceFiles\MainWindow.xaml.cs:line 29
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

this is inside the packet class when the server tries to call it

**Comment by OGarland001** [comment]
see this fix. we will follow the same format for all sends and receives
https://github.com/OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1/commit/1debbdcf69d7a97bfc3bb31818ac56bc7293058b
